" =======================================
" vimrc
"
" This file will be sourced before anything else
" Use it to configure things that will be overridden by default settings
" =======================================

" Uncomment this if you want the solarized color scheme
" or replace solarized with a different color scheme from:
" https://github.com/flazz/vim-colorschemes/tree/master/colors
" let g:cola_colorscheme='solarized'
