#!/usr/bin/env bash

############################ BASIC TOOLS
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
BOLD=$(tput bold)
NORMAL=$(tput sgr0)
RESET='\033[0;m'

info() {
  printf "${BLUE}${BOLD}==>${NORMAL}${BOLD} ${1}${RESET}\n"
}

warn() {
  printf "${YELLOW}${BOLD}Warning:${NORMAL} ${1}${RESET}\n"
}

error() {
  printf "${RED}${BOLD}Error:${NORMAL} ${1}${RESET}\n"
}

die() {
  error "${1}"
  exit 1
}

############################ FUNCTIONS
xdg_error() {
  if [[ $1 == "XDG_CONFIG_HOME" ]]; then
    export_msg="try: echo \"export XDG_CONFIG_HOME=$HOME/.config\" >> $shell_startup"
  elif [[ $1 == "XDG_DATA_HOME" ]]; then
    export_msg="try: echo \"export XDG_DATA_HOME=$HOME/.local/share\" >> $shell_startup"
  elif [[ $1 == "XDG_CACHE_HOME" ]]; then
    export_msg="try: echo \"export XDG_CACHE_HOME=$HOME/.cache\" >> $shell_startup"
  fi

  error "\$$1 must be set to use these vim config files. \n$export_msg \
  \nSee: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html"
}

do_backup() {
  info "Backing up your original vim configuration"
  # msg=$(date +%Y-%m-%d_%s)
  msg="original"
  for file in "${@}"; do
    if [[ -e "${file}" ]] || [[ -L "${file}" ]]; then
      mv -v "${file}" "${file}.${msg}"
    fi
  done
}

clone_repo() {
  local repo_path="$1"
  local repo_uri="$2"
  local repo_branch="$3"
  local repo_name="$4"

  info "Installing $repo_name"
  mkdir -p "$repo_path"
  git clone -b "$repo_branch" "$repo_uri" "$repo_path"
}

update_repo() {
  local repo_path="$1"
  local repo_uri="$2"
  local repo_branch="$3"
  local repo_name="$4"

  info "Updating $repo_name"

  cd "$repo_path" && git pull origin "$repo_branch"
}

install_vim_plug() {
  info "Installing vim-plug"

  [[ -e "${1}/bundle" ]] && rm -rf "${1}/bundle"

  curl -fLo "${1}/autoload/plug.vim" --create-dirs "${VIM_PLUG_URI}"
}

create_local_files() {
  for file in "${@}"; do
    local_file="${XDG_CONFIG_HOME}/vim/${file}"
    touch "${local_file}"
  done
}

link_files() {
  for file in "${@}"; do
    dot_file="${HOME}/.${file}"
    ln -vs "${COLA_CONFIG_HOME}/${file}" "${dot_file}"
    
    if hash nvim &>/dev/null; then
      ln -s "${COLA_CONFIG_HOME}" "${HOME}/.nvim"
      ln -s "${COLA_CONFIG_HOME}/vimrc" "${HOME}/.nvimrc"
    fi
  done
}

install_go_deps() {
  if hash go &>/dev/null; then
    info "Installing golang dependencies..."
    gopackages="\
      github.com/golang/lint/golint \
      github.com/jstemmer/gotags \
      github.com/kisielk/errcheck \
      github.com/nsf/gocode \
      golang.org/x/tools/cmd/godoc \
      golang.org/x/tools/cmd/goimports \
      golang.org/x/tools/cmd/gorename \
      golang.org/x/tools/cmd/oracle \
      golang.org/x/tools/cmd/vet \
      "

    for p in $gopackages; do
      echo "Installing ${p}..."
      go get -f -u "${p}"
    done
    ln -sfh "${COLA_CONFIG_HOME}/snippets/go.snip" "${XDG_DATA_HOME}/vim/snippets"
  fi
}

install_plugins() {
  local vimrc="$1"
  local vimcmd="$2"
  vim -u "${vimrc}" +"$vimcmd" +'qall!'
  if hash nvim &>/dev/null; then
    nvim -u "${vimrc}" +"$vimcmd" +'qall!'
  fi
}

bootstrap_plugins() {
  info "Installing plugins & plugin dependencies"
  local vimrc="$1"
  install_plugins "${vimrc}" "silent! PlugInstall!|silent! GoInstallBinaries!|"
}

update_plugins() {
  info "Updating plugins & plugin dependencies"
  install_plugins "$1" "silent! PlugUpgrade!|"
  install_plugins "$1" "silent! PlugClean!|PlugUpdate!|"
}

write_bootstrap_config() {
  cat >"${1}" <<EOF
if !has('nvim')
  set nocompatible
endif

if empty("\$XDG_CACHE_HOME")
  let \$XDG_CACHE_HOME = "$HOME/.cache"
endif

if empty("\$XDG_CONFIG_HOME")
  let \$XDG_CONFIG_HOME = "$HOME/.config"
endif

if empty("\$XDG_DATA_HOME")
  let \$XDG_DATA_HOME = "$HOME/.local/share"
endif

set runtimepath=\$XDG_CONFIG_HOME/vim,\$XDG_DATA_HOME/vim/plugged,\$XDG_CONFIG_HOME/vim/after,\$VIM,\$VIMRUNTIME 
set directory=\$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=\$XDG_CACHE_HOME/vim,~/,/tmp
set undodir=\$XDG_CACHE_HOME/vim/undo,~/,/tmp

let g:session_autosave = 'no'

source \$XDG_CONFIG_HOME/vim/Plug.vim
EOF
}

############################  SETUP PARAMETERS
[[ -z $XDG_CONFIG_HOME ]] && xdg_error "XDG_CONFIG_HOME" && should_die=1
[[ -z $XDG_CACHE_HOME ]] && xdg_error "XDG_CACHE_HOME" && should_die=1
[[ -z $XDG_DATA_HOME ]] && xdg_error "XDG_DATA_HOME" && should_die=1
[[ $should_die -eq 1 ]] && exit 1

COLA_APP_NAME="speed-cola"
[[ -z "$COLA_CONFIG_HOME" ]] && COLA_CONFIG_HOME="${XDG_CONFIG_HOME}/vim"
[[ -z "$COLA_REPO_URI" ]] && COLA_REPO_URI="https://github.com/mkwmms/speed-cola"
[[ -z "$COLA_REPO_BRANCH" ]] && COLA_REPO_BRANCH='master'

VIM_PLUG_URI='https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

if [[ -e "$HOME/.zshrc" ]]; then
  shell_startup="$HOME/.zshrc"
elif [[ -e "$HOME/.bashrc" ]]; then
  shell_startup="$HOME/.bashrc"
fi

repo_vimrc_files="vimrc"
hash gvim &>/dev/null && repo_vimrc_files="vimrc gvimrc"

local_vimrc_files="vimrc.local vimrc.local.before"

############################ MAIN()
if [[ -e "${COLA_CONFIG_HOME}" ]]; then
  cd "${COLA_CONFIG_HOME}"
  should_update_repo=false
  [[ $(git remote -v) =~ "${COLA_REPO_URI}" ]] && should_update_repo=true
else
  should_update_repo=false
fi

if [[ $should_update_repo == true ]]; then
  mkdir -p "${XDG_CONFIG_HOME}"/vim &>/dev/null
  mkdir -p "${XDG_CACHE_HOME}"/vim/{undo,swap,backup} &>/dev/null
  mkdir -p "${XDG_DATA_HOME}"/vim/{sessions,snippets} &>/dev/null
  
  update_repo "${COLA_CONFIG_HOME}" \
              "${COLA_REPO_URI}" \
              "${COLA_REPO_BRANCH}" \
              "${COLA_APP_NAME}"

  update_plugins "${COLA_CONFIG_HOME}/vimrc"
else
  do_backup "${HOME}/.vim" \
            "${HOME}/.vimrc" \
            "${HOME}/.gvimrc" \
            "${HOME}/.nvimrc" \
            "${HOME}/.nvim" \
            "${XDG_CONFIG_HOME}/nvim" \
            "${COLA_CONFIG_HOME}"

  mkdir -p "${XDG_CONFIG_HOME}"/vim &>/dev/null
  mkdir -p "${XDG_CACHE_HOME}"/vim/{undo,swap,backup} &>/dev/null
  mkdir -p "${XDG_DATA_HOME}"/vim/{sessions,snippets} &>/dev/null

  clone_repo "${COLA_CONFIG_HOME}" \
             "${COLA_REPO_URI}" \
             "${COLA_REPO_BRANCH}" \
             "${COLA_APP_NAME}"

  link_files "${repo_vimrc_files}"
  # create_local_files "${local_vimrc_files}"
  
  install_vim_plug "${COLA_CONFIG_HOME}"

  install_go_deps

  # NOTE: I don't think there is another way to do this...
  bootstrap_vimrc="/tmp/vimrc.bootstrap"
  write_bootstrap_config "${bootstrap_vimrc}"
  bootstrap_plugins "${bootstrap_vimrc}"
  #rm -rf "${bootstrap_vimrc}"
fi
